import { Metadata } from 'next';
import React from 'react';


export const metadata: Metadata = {
    title: "Nazar Optics",
    description: "Generated by create next app",
  }; 

const DashboardLayout = ({children}: {children: React.ReactNode}) => {
    return (
        <div>
            {children}
        </div>
    );
};

export default DashboardLayout;