import { NextUiProvider } from "@/lib/Providers/NextUiProvider";
import StoreProvider from "@/lib/Providers/StoreProvider";
import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";


const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nazar Optics",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={outfit.className} suppressHydrationWarning={true}>
        <StoreProvider>
          <NextUiProvider>
            {children}
          </NextUiProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
