import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/lib/Providers/StoreProvider";
import Navbar from "@/components/shared/Navbar/Navbar";

const outfit = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Nazar Optics",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={outfit.className}  suppressHydrationWarning={true}>
        <StoreProvider>
        <Navbar/>
          {children}</StoreProvider>
      </body>
    </html>
  );
}
